export const pricingPlans = [
  {
    id: "free",
    name: "Free",
    priceMonthly: 0,
    currency: "USD",
    interval: "month",
    label: "$0",
    cta: { label: "Get started", href: "/signup?plan=free" },
    continuance: "Renews monthly for $0; upgrade anytime.",
    features: [
      "Basic creator profile",
      "Public feed access",
      "1 live session per week (RTMP)",
      "Basic chat",
      "Community support",
    ],
  },
  {
    id: "merchant",
    name: "Merchant",
    priceMonthly: 20,
    currency: "USD",
    interval: "month",
    label: "$20",
    cta: { label: "Subscribe", href: "/signup?plan=merchant" },
    continuance: "Auto-renews monthly at $20; cancel anytime.",
    features: [
      "All Free features",
      "Unlimited live sessions (RTMP)",
      "In-browser go-live (WebRTC)",
      "Product catalog + cart",
      "Promo overlays & callouts",
      "Email support",
    ],
  },
  {
    id: "enterprise",
    name: "Enterprise",
    priceMonthly: 45,
    currency: "USD",
    interval: "month",
    label: "$45",
    cta: { label: "Contact sales", href: "/signup?plan=enterprise" },
    continuance: "Auto-renews monthly at $45; cancel or adjust seats anytime.",
    features: [
      "All Merchant features",
      "Multiple hosts & roles",
      "Priority support",
      "Advanced analytics",
      "Custom branding",
      "SLA & onboarding assistance",
    ],
  },
];


